### PR TITLE
Initial full stack demonstration

### LINKED ISSUE #13: Create react-based sentence rendering demo
We now have the bare basic NLP processing of caption streams, it's time to show it off!

Some components of this first demo:

1. Build in react
2. Real time rendering of new sentences / content
3. Ability to filter rendered data by time ranges

I think the initial view should be in terms of the named entities -- clicking on a named entity should expose the specific sentences that contain that entity.

### PR DESCRIPTION
**Pull request by slifty**
This is not beautiful, but it does show off basic functionality.  This is the PR for the demo that was made in early December, but the code is a bit more organized and now properly linted.  Here are some screen shots of what it does.

Base page, showing frequency counts for "all time" (note that all time here was about a two hour window)
image

If you click a bar, you go to detail view that looks something like this

image

The interfaces are in react, they pull data from a graphQL api.

This resolves #13

### CODE REVIEW

**Comment by reefdog** [comment]
This works and marks a great prototype to iterate from. The installation instructions need updating but rather than force that upon this PR I'll handle it via #18.

**Comment by reefdog** [comment]
Update: well, partially works. Front page Keyword Counts are filling in:
1-keyword-counts

…but drilling into an entity detail nets blank boxes:
2-entity-detail

Also, [five console errors on the front page](https://gist.github.com/reefdog/73db12901b2184ca5d5cb5155d2653a6) and [three on the entity page](https://gist.github.com/reefdog/5e5b258d5271b4ec55b79c1c265432ff).

@slifty Do you want me to merge this in anyway and we can continue addressing this? I don't have any complaints about the larger architecture this PR scaffolds and prototypes.

**Comment by slifty** [comment]
Thank you -- I'm going to try to replicate locally and fix the PR before we merge!

Note that not all elements work (e.g. Recent Transcript / Recent Entities) but the drilldowns *should*

**Comment by reefdog** [comment]
Ping me if you want to pair on it. Could be something env-specific that's not rearing its head more obviously.

**Comment by reefdog** [comment]
SORRY accidental close!

**Comment by slifty** [comment]
All righty -- I had added a bunch of propType details without realizing that null is not a valid value for required types.  There were some other issues related to iterated DOM elements that needed keys.  This should all be fixed up now; I'm going to merge this so we can keep on going!

**Pull request merged**
